apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-{{ include "fastapi-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: fastapi-poc
    version: {{.Chart.AppVersion}}
data:
  POSTGRES_DB: ZmFzdGFwaQ==
  POSTGRES_USER: ZmFzdGFwaQ==
  POSTGRES_PASSWORD: ZmFzdGFwaQ==
  DATABASE_URL: cG9zdGdyZXNxbDovL2Zhc3RhcGk6ZmFzdGFwaUBwb3N0Z3Jlcy1zZXJ2aWNlLmZhc3RhcGkuc3ZjLmNsdXN0ZXIubG9jYWwvZmFzdGFwaQ==
